version: "3.5"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=keystone
      - POSTGRES_PASSWORD=keystone
      - POSTGRES_DB=keystone
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - keystone_postgres_volume:/var/lib/postgresql/data

volumes:
  keystone_postgres_volume: {}
