# Generated by Django 4.2.5 on 2024-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0002_become_arch_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="collection_type",
            field=models.CharField(
                choices=[
                    ("AIT", "Archive-It"),
                    ("SPECIAL", "Special"),
                    ("CUSTOM", "Custom"),
                ],
                max_length=16,
            ),
        ),
    ]
