# Generated by Django 4.2.7 on 2024-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0003_alter_collection_collection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtype",
            name="parameters_schema",
            field=models.JSONField(null=True),
        ),
    ]
