# Generated by Django 4.2.7 on 2024-04-30 19:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="metadata",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
