# Generated by Django 4.2.7 on 2024-05-06 16:32

from django.db import migrations, models
import keystone.validators


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0006_alter_collection_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[keystone.validators.validate_username],
            ),
        ),
    ]
