# Generated by Django 4.2.7 on 2024-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0008_remove_collection_latest_dataset_dataset_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtype",
            name="code_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobtype",
            name="info_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
