# Generated by Django 4.2.15 on 2024-09-09 19:55

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0014_user_update_trigger_allow_account_mutation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                models.F("metadata__input_spec"), name="metadata__input_spec_idx"
            ),
        ),
    ]
