# Generated by Django 4.2.15 on 2024-09-23 21:03

import django.core.serializers.json
from django.db import migrations, models
import django_resized.forms
import keystone.validators


class Migration(migrations.Migration):
    dependencies = [
        ("keystone", "0016_collection_metadata__input_spec_unique_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="info_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[250, None],
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="metadata",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                validators=[keystone.validators.validate_and_clean_collection_metadata],
            ),
        ),
    ]
