
POST http://127.0.0.1:8000/private/api/collection
Content-Type: application/json
X-API-Key: supersecret

{
  "name": "string",
  "collection_type": "AIT"
}

###
POST http://127.0.0.1:8000/private/api/collection
Content-Type: application/json
X-API-Key: supersecret

{
  "job_type_name": "string",
  "job_type_version": "string",
  "username": "avdempsey",
  "input_bytes": 100000,
  "parameters": {}
}